config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :students
  resources :courses
  resources :classrooms

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  #Relacionamentos
  belongs_to :student, :class_name => Student, :foreign_key => :student_id
  belongs_to :course, :class_name => Course, :foreign_key => :course_id
  validates :student, presence: true
  #Define valor padrão para a data da matrícula
  after_initialize :default_values
  private
  def default_values
      self.entry_at = Time.now
  end
  #Data/Hora somente leitura
  attr_readonly :entry_at
end

app/models/course.rb
class Course < ActiveRecord::Base
	 #Validação do tamanho dos campos
	 validates_length_of :name, minimum: 5, maximum: 45, allow_blank: false
	 validates_length_of :description, minimum: 1, maximum: 45, allow_blank: false
	 
	 #Validação de campos únicos
	 validates_uniqueness_of :name
	 validates_uniqueness_of :description

	 #Foreign Key 
	 has_many :classroom, :dependent => :destroy

end

app/models/student.rb
class Student < ActiveRecord::Base
	 #Validação do tamanho dos campos
	 validates_length_of :name, minimum: 5, maximum: 45, allow_blank: false
	 validates_length_of :register_number, minimum: 1, maximum: 45, allow_blank: false

	 #Validação dos campos únicos
	 validates_uniqueness_of :name
	 validates_uniqueness_of :register_number

	 #Foreign Key 
	 has_many :classroom, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
   def classroom_params
      params.require(:classroom).permit(:student_id, :course_id, :entry_at)
   end

   def new
      @classroom = Classroom.new
      @student = Student.all 
      @course = Course.all 
   end

   def create
     @classroom = Classroom.new(classroom_params)
 
     if @classroom.save
       redirect_to @classroom, notice: "Matrícula foi criada."
     else
       flash[:alert] = "Matrícula não pode ser criada."
       render "new"
     end
   end

   def show
     @classroom = Classroom.find(params[:id])
   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
   private def course_params
      params.require(:course).permit(:name, :description)
   end

   def new
      @course = Course.new
   end

   def create
     @course = Course.new(course_params)
 
     if @course.save
       redirect_to @course, notice: "Curso foi criado."
     else
       flash[:alert] = "Curso não pode ser criado."
       render "new"
     end
   end

   def show
     @course = Course.find(params[:id])
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
   private def student_params
      params.require(:student).permit(:name, :register_number)
   end

   def new
      @student = Student.new
   end

   def create
     @student = Student.new(student_params)
 
     if @student.save
       redirect_to @student, notice: "Estudante foi criado."
     else
       flash[:alert] = "Estudante não pode ser criado."
       render "new"
     end
   end

   def show
     @student = Student.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/new.html.erb
<h2>Nova matrícula</h2>
<%= form_for(@classroom) do |f| %>
  <%= render 'shared/errors', object: f.object %>
  <p>
    <%= f.label :student_id, "Estudante" %><br />
    <!--<%= f.collection_select(:student,Student.all,:id,:name,prompt: true) %>-->
    <%= f.select :student_id, Student.all.collect {|c| [c.name, c.id]} %>
  <p>
    <%= f.label :course_id, "Curso" %><br />
    <!--<%= f.collection_select(:course,Course.all,:id,:name,prompt: true) %>-->
    <%= f.select :course_id, Course.all.collect {|c| [c.name, c.id]} %>
  </p>
  <p>
    <%= f.label :entry_at, "Data/Hora" %><br />
    <%= f.datetime_select(:entry_at) %>
  </p>
  <p>
     <%= f.submit "Criar matrícula" %>
  </p>
<% end %>

app/views/classrooms/show.html.erb
<h2><%= @classroom.student.name %></h2>
<p><%= @classroom.course.name %></p>
<p><%= @classroom.entry_at %></p>

app/views/courses/new.html.erb
<h2>Novo Curso</h2>
<%= form_for(@course) do |f| %>
  <%= render 'shared/errors', object: f.object %>
  <p>
    <%= f.label :name, "Nome" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description, "Descrição" %><br />
    <%= f.text_field :description %>
  </p>
  <p>
     <%= f.submit "Criar curso" %>
  </p>
<% end %>

app/views/courses/show.html.erb
<h2><%= @course.name %></h2>
<p><%= @course.description %></p>

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Novo Estudante', new_student_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
  <a class="navbar-brand" href="#">ProficiencyTest</a>
</div>
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <li class="active"><a href="#">Início</a></li>
    <li><%= link_to 'Novo Estudante', new_student_path %></li>
    <li><%= link_to 'Novo Curso', new_course_path %></li>
    <li><%= link_to 'Nova Matrícula', new_classroom_path %></li>  </ul>
</div>
</div>
</div>

<div class="container">
	<%= render 'shared/messages' %>
	<%= yield %>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      O formulário contém <%= pluralize(object.errors.count, "erro") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_messages.html.erb
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

app/views/students/new.html.erb
<h2>New Student</h2>
<%= form_for(@student) do |f| %>
  <%= render 'shared/errors', object: f.object %>
  <p>
    <%= f.label :name, "Nome" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :register_number, "Número do Registro" %><br />
    <%= f.text_field :register_number %>
  </p>
  <p>
     <%= f.submit "Criar estudante" %>
  </p>
<% end %>

app/views/students/show.html.erb
<h2><%= @student.name %></h2>
<p><%= @student.register_number %></p>